# Generated by Django 5.2.11 on 2026-02-26 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clock_event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClockValidationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("USED", "Utilisé"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "clock_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_code",
                        to="clock_event.clockevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="clock_valid_code_35ff96_idx"
                    ),
                    models.Index(
                        fields=["expires_at", "status"],
                        name="clock_valid_expires_38091c_idx",
                    ),
                ],
            },
        ),
    ]
