services:
  init-env:
    image: bash:5.2
    container_name: timemanager_init_env
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: ["bash", "-lc", "chmod +x docker/generate_env.sh && ./docker/generate_env.sh"]

  db:
    image: postgres:16
    container_name: timemanager_db
    depends_on:
      init-env:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: timemanager-backend:local
    container_name: timemanager_web
    depends_on:
      init-env:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
      # monte ton entrypoint local (pratique si tu le modifies sans rebuild)
      - ./docker/entrypoint.sh:/app/docker/entrypoint.sh:ro
    ports:
      - "8000:8000"
    entrypoint: ["/bin/bash", "/app/docker/entrypoint.sh"]
    command: ["gunicorn", "primeBank.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]

  nginx:
    image: nginx:1.27
    container_name: timemanager_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  static_data:
  media_data: