# Generated by Django 5.2.11 on 2026-02-12 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teams",
            options={"verbose_name": "Team", "verbose_name_plural": "Teams"},
        ),
        migrations.AddField(
            model_name="teams",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Membres",
            ),
        ),
    ]
