# Generated by Django 5.2.11 on 2026-02-13 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0003_alter_department_options_alter_department_director_and_more",
        ),
        ("teams", "0002_alter_teams_options_teams_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teams",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.AlterField(
            model_name="teams",
            name="description",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="teams",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="teams",
            index=models.Index(
                fields=["name", "created_at"], name="teams_name_706cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teams",
            index=models.Index(fields=["-created_at"], name="teams_created_40fe06_idx"),
        ),
    ]
