# Generated by Django 5.2.11 on 2026-02-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plannings", "0001_initial"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planning",
            options={"ordering": ["-start_datetime"]},
        ),
        migrations.RemoveField(
            model_name="planning",
            name="team_id",
        ),
        migrations.AddField(
            model_name="planning",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plannings",
                to="teams.teams",
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="planning_type",
            field=models.CharField(
                choices=[
                    ("SHIFT", "Shift"),
                    ("MEETING", "Meeting"),
                    ("PTO", "Paid time off"),
                ],
                default="SHIFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planning",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
    ]
