# Generated by Django 5.2.11 on 2026-02-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shift", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_start_time", models.TimeField(blank=True, null=True)),
                ("new_end_time", models.TimeField(blank=True, null=True)),
                ("cancelled", models.BooleanField(default=False)),
                (
                    "reason_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SICK", "Maladie"),
                            ("LEAVE", "Congé"),
                            ("TRAINING", "Formation"),
                            ("MEETING", "Réunion"),
                            ("CANCELLED", "Annulation"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reason_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override",
                        to="shift.shift",
                    ),
                ),
            ],
        ),
    ]
