# Generated by Django 5.2.11 on 2026-02-25 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("WORK", "Travail"),
                            ("BREAK", "Pause"),
                            ("HOLIDAY", "Jour férié"),
                            ("OFF", "Repos"),
                        ],
                        default="WORK",
                        max_length=10,
                    ),
                ),
                ("overridden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="assignment.scheduleassignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="shift_shift_user_id_545790_idx"
                    ),
                    models.Index(
                        fields=["shift_type"], name="shift_shift_shift_t_991d23_idx"
                    ),
                ],
                "unique_together": {("user", "date", "start_time", "end_time")},
            },
        ),
    ]
