# Generated by Django 5.2.11 on 2026-02-09 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("READ", "Read"),
                            ("WRITE", "Write"),
                            ("APPROVE", "Approve"),
                            ("ADMIN", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "granted_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "granted_to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["permission_type"],
                        name="permissions_permiss_1fa87a_idx",
                    ),
                    models.Index(
                        fields=["granted_to_user"],
                        name="permissions_granted_371366_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__gte", models.F("start_date")),
                            ("end_date__isnull", True),
                            _connector="OR",
                        ),
                        name="permission_end_date_after_start_date",
                    )
                ],
            },
        ),
    ]
