# Generated by Django 5.2.11 on 2026-02-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permission",
            name="permission_end_date_after_start_date",
        ),
    ]
