# Generated by Django 5.2.11 on 2026-02-12 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_alter_department_director"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="director",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="directed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Directeur",
            ),
        ),
        migrations.AlterModelTable(
            name="department",
            table="departments",
        ),
    ]
