# Generated by Django 5.2.11 on 2026-02-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0003_alter_department_options_alter_department_director_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
