# Generated by Django 5.2.11 on 2026-02-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("week_pattern", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "slot_type",
                    models.CharField(
                        choices=[("WORK", "Travail"), ("BREAK", "Pause")],
                        default="WORK",
                        max_length=10,
                    ),
                ),
                (
                    "week_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="week_pattern.weekpattern",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["week_pattern", "weekday"],
                        name="time_slot_p_week_pa_8575b3_idx",
                    )
                ],
            },
        ),
    ]
